FROM python:3.10

WORKDIR /code

COPY ./backend/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./backend /code/backend

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt -e /code/backend

CMD ["uvicorn", "backend.src.run:app", "--host", "0.0.0.0", "--port", "8000"]
